User.create!(name: '斎藤',age: 14)
User.create!(name: '鈴木',age: 24)
User.create!(name: '佐藤',age: 20)
User.create!(name: '佐々木',age: 39)
User.create!(name: '島田',age: 43)
User.create!(name: '須藤',age: 22)
User.create!(name: '祥畑',age: 21)
